### ISSUE TITLE
ExchangeItem transition not working properly

### ISSUE THREAD

**Issue by arnauddieumegard** [eclipse/capella-sss-transition#93]
- When applying "to SA" transition on an EI located inside a hierarchy of DataPkg, the transtioned EI does not keeps the DataPkg hierarchy. To also check in other transitions.
- `ExchangeItem`s assigned to a Function port are not transitioned using SSST. This transition shall function also on other ports (e.g. Components/Entities ports, all functions ports...)

**Comment by etraisnel2** [comment]
Second part moved to https://github.com/eclipse/capella/issues/2487
But tests for the corresponding issue shall be achieved here
